### ISSUE TITLE
Type error in the Python code?

### ISSUE THREAD

**Issue by Mbodin** [TDiazT/CoqR-Tester#47]
Hi Tomás.
I just ran the tests and got the following result.
I am at commit 74f6506bb60281590a88e12d2ff3366bec8505d2 (it is the last one on Github, I think).
Martin.

``` bash
$ python3 -m coqr.scripts.run_all ../tests/testExtra.R out/testExtra.json
Interpreting tests in ../tests/testExtra.R
Running R interpreter...
Interpreting line 0
[…]
Interpreting line 134
line 1:20 mismatched input '...' expecting {'-', '+', '!', '~', 'function', '(', '{', 'if', 'for', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', HEX, INT, FLOAT, COMPLEX, STRING, ID}
Interpreting line 135
[…]
Interpreting line 289
line 1:35 extraneous input '<<-' expecting {<EOF>, ';', '[[', '[', '::', ':::', '$', '@', '^', '-', '+', ':', '*', '/', '>', '>=', '<', '<=', '==', '!=', '!', '&', '&&', '|', '||', '~', '<-', '=', '->', 'function', '(', '{', 'if', 'else', 'for', 'in', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', ',', '...', HEX, INT, FLOAT, COMPLEX, STRING, ID, USER_OP, NL}
line 1:45 extraneous input '->>' expecting {<EOF>, ';', '[[', '[', '::', ':::', '$', '@', '^', '-', '+', ':', '*', '/', '>', '>=', '<', '<=', '==', '!=', '!', '&', '&&', '|', '||', '~', '<-', '=', '->', 'function', '(', '{', 'if', 'else', 'for', 'in', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', ',', '...', HEX, INT, FLOAT, COMPLEX, STRING, ID, USER_OP, NL}
Interpreting line 290
[…]
Interpreting line 321
Finished in 112.373904 seconds
Running Coq interpreter...
Interpreting line 0
[…]
Interpreting line 134
line 1:20 mismatched input '...' expecting {'-', '+', '!', '~', 'function', '(', '{', 'if', 'for', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', HEX, INT, FLOAT, COMPLEX, STRING, ID}
Interpreting line 135
[…]
Interpreting line 289
line 1:35 extraneous input '<<-' expecting {<EOF>, ';', '[[', '[', '::', ':::', '$', '@', '^', '-', '+', ':', '*', '/', '>', '>=', '<', '<=', '==', '!=', '!', '&', '&&', '|', '||', '~', '<-', '=', '->', 'function', '(', '{', 'if', 'else', 'for', 'in', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', ',', '...', HEX, INT, FLOAT, COMPLEX, STRING, ID, USER_OP, NL}
line 1:45 extraneous input '->>' expecting {<EOF>, ';', '[[', '[', '::', ':::', '$', '@', '^', '-', '+', ':', '*', '/', '>', '>=', '<', '<=', '==', '!=', '!', '&', '&&', '|', '||', '~', '<-', '=', '->', 'function', '(', '{', 'if', 'else', 'for', 'in', 'while', 'repeat', '?', 'next', 'break', 'NULL', 'NA', 'Inf', 'NaN', 'TRUE', 'FALSE', ',', '...', HEX, INT, FLOAT, COMPLEX, STRING, ID, USER_OP, NL}
Interpreting line 290
[…]
Interpreting line 321
Finished in 513.002465 seconds
Processing R output
Processing Coq output
Comparing
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/scripts/run_all.py", line 104, in <module>
    comparison = compare_processed_outputs(r_process, coq_process)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/scripts/run_all.py", line 60, in compare_processed_outputs
    return comparator.compare_results(processed_coq, processed_r)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/comparators/Comparator.py", line 58, in compare_results
    comparisons = self.compare_sub_reports(report_1.sub_reports, report_2.sub_reports)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/comparators/Comparator.py", line 40, in compare_sub_reports
    comparison = self.compare(coq_sub_report.processed_output, r_sub_report.processed_output)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/comparators/Comparator.py", line 27, in compare
    return out1.compare_to(out2)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/reports/results.py", line 156, in compare_to
    return other.compare_to_vector(self)
  File "/home/mbodin/Dropbox/CMM/Code/ProveR/compare/coqr/reports/results.py", line 187, in compare_to_vector
    if isnan(n1) and isnan(n2):
TypeError: a float is required
```

**Comment by TDiazT** [comment]
Yup, fixed it. Caused by None (NA values)
